config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  shallow do
    root 'pages#home'

    devise_for :users, controllers: {
      omniauth_callbacks: 'devise/my_omniauth_callbacks',
      registrations: 'devise/my_registrations',
    }

    authenticate :user, ->(u) { u.superadmin? } do
      mount Sidekiq::Web => '/sidekiq'
    end

    get 'pages/home'
    get 'sign-in-development/:id', to: 'pages#sign_in_development', as: :sign_in_development
    get 'set_locale', to: 'application#set_locale'
    get 'sample-error', to: 'pages#sample_error'
    get 'sample-error-in-javascript', to: 'pages#sample_error_in_javascript'
    get 'sample-error-in-javascript-ajax', to: 'pages#sample_error_in_javascript_ajax'
    post 'notify-javascript-error', to: 'pages#notify_javascript_error'
    get 'sample-error-in-sidekiq', to: 'pages#sample_error_in_sidekiq'
    get '/test', to: 'pages#test'

    resource :contact

    resources :happenings do
      collection do
        post :search
        get :index_for_location_and_activities
        post :search_for_location_and_activities
      end
    end

    resource :my_account do
      get :change_email
      get :change_password
      patch :update_password
      get :change_language
      get :edit
      patch :update
    end

    resources :clubs do
      collection do
        post :search
      end
      member do
        post :search_happenings
      end
    end

    resource :my_club do
      patch :submit_choose
      delete :remove_me_from
    end
    resources :club_users do
      collection do
        post :search
      end
    end

    namespace :admin do
      get 'dashboard', to: 'dashboard#index'
      resources :users
      resources :activities
      resources :clubs do
        resources :activity_clubs
        collection do
          post :search
        end
        member do
          post :search_happenings
        end
        resources :happenings, only: %i[new create]
      end
      resources :venues
      resources :happenings, except: %i[new create] do
        member do
          get :edit_recurrence
          patch :update_recurrence
        end
        collection do
          get :parse_url
        end
        resources :discipline_happenings
      end
      resources :disciplines do
        resources :discipline_requirements
      end
      resources :requirements
    end
  end
end

app/models/happening.rb
class Happening < ApplicationRecord
  extend Mobility
  translates :name, :description

  FIELDS = %i[name description website recurrence start_date end_date].freeze

  serialize :recurrence
  attr_accessor :existing_or_new

  belongs_to :venue
  accepts_nested_attributes_for :venue
  belongs_to :club

  has_many :discipline_happenings, dependent: :destroy

  validates :name, :start_date, :end_date, presence: true
  validate :_end_date_greater_or_equal_start_date

  before_validation :_default_values_on_create, on: :create

  def _end_date_greater_or_equal_start_date
    return if end_date.blank? || start_date.blank?
    return if end_date >= start_date

    errors.add :end_date, t('can_not_be_less_than_item_name', item_name: Happening.human_attribute_name(:start_date))
  end

  def multi_day?
    end_date != start_date
  end

  def _default_values_on_create
    self.end_date ||= start_date
  end
end

app/controllers/admin/happenings_controller.rb
class Admin::HappeningsController < Admin::BaseController
  before_action :_set_happening, except: %i[index new create parse_url]

  def index
    @happenings = Happening.all
  end

  def show; end

  def new
    @happening = Happening.new(
      club_id: params[:club_id]
    )
    render partial: 'form', layout: false
  end

  def edit
    render partial: 'form', layout: false
  end

  def edit_recurrence
    @recurrence_form = RecurrenceForm.new(
      happening: @happening,
      day: @happening.start_date.wday,
      every: t('recurrences_every').first.first,
      total: 1,
      hour: @happening.discipline_happenings.order(start_time: :asc).first&.start_time&.hour,
      min: @happening.discipline_happenings.order(start_time: :asc).first&.start_time&.min,
    )
    render partial: 'recurrence_form', layout: false
  end

  def update_recurrence
    @recurrence_form = RecurrenceForm.new(
      *_recurrence_form_params.merge(
        happening: @happening,
      )
    )
    return if params[:button] == 'preview'

    update_and_render_or_redirect_in_js(
      @recurrence_form,
      _recurrence_form_params, admin_happening_path(@happening),
      'recurrence_form',
      helpers.t_notice_count('successfully_created', Happening, @recurrence_form.preview.size),
    )
  end

  # JS
  def create
    @happening = Happening.new(
      club_id: params[:club_id]
    )
    update_and_render_or_redirect_in_js @happening, _happening_params, ->(id) { admin_happening_path(id) }
  end

  # JS
  def update
    update_and_render_or_redirect_in_js @happening, _happening_params, admin_happening_path(@happening)
  end

  def destroy
    @happening.destroy!
    redirect_to admin_happenings_path, notice: helpers.t_notice('successfully_deleted', Happening)
  end

  def parse_url
    result = ParseUrl.new(params[:url]).perform
    if result.success?
      render json: result.data[:json]
    else
      render json: { error: result.message }
    end
  end

  def _set_happening
    @happening = Happening.find params[:id]
  end

  def _happening_params
    params.require(:happening).permit(
      *Happening::FIELDS, :existing_or_new, :venue_id, :club_id,
      venue_attributes: Venue::FIELDS,
    )
  end

  def _recurrence_form_params
    params.require(:recurrence_form).permit(*RecurrenceForm::FIELDS)
  end
end

app/controllers/happenings_controller.rb
class HappeningsController < ApplicationController
  before_action :_set_happening, except: %i[index index_for_location_and_activities search_for_location_and_activities]

  def index
    redirect_to root_path
  end

  def index_for_location_and_activities
    @datatable = HappeningsForActivityNamesDatatable.new view_context
  end

  def search_for_location_and_activities
    render json: HappeningsForActivityNamesDatatable.new(view_context)
  end

  def show; end

  def _set_happening
    @happening = Happening.find params[:id]
  end

  def _happening_params
    params.require(:happening).permit(
      *Happening::FIELDS, :existing_or_new, :venue_id, :club_id,
      venue_attributes: Venue::FIELDS,
    )
  end

  def _search_happenings_params
    params.require(:search_happenings).permit(
      :venue_id, :activity_id
    )
  end
end

app/views/happenings/index_for_location_and_activities.html.erb
<%
  no_cache
  breadcrumb Happening.model_name.human(count: 2) => nil

  names_array = params[:activity_names]
  names_array = names_array.values if names_array.respond_to? :values
%>

<% @datatable.activities.each do |activity| %>
  <span class='show-on-hover'>
    <span class='badge badge-secondary pl-4'>
      <%= activity.name %>
      <% remove_path = index_for_location_and_activities_happenings_path(params.merge(activity_names: (names_array || []) - [activity.name])) %>
      <%= link_to remove_path do %>
        <i class='demo-icon icon-cancel show-on-hover-target btn-danger' title='<%= t_crud('drop', Activity) %>'></i>
      <% end %>
    </span>
  </span>
<% end %>
<div class='dropdown d-inline'>
  <a class='btn btn-se dropdown-toggle' href='#' role='button' id='dropdownAddActivity' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>
    <%= t('select_item_name', item_name: Activity.model_name.human(count: 2)) %>
  </a>
  <div class='dropdown-menu' aria-labelledby='dropdownAddActivity'>
    <% Activity.i18n.where.not(name: names_array).each do |activity| %>
      <% add_path = index_for_location_and_activities_happenings_path(params.except(:controller, :action, :commit).merge(activity_names: (names_array || []) + [activity.name])) %>
      <% add_related_path = index_for_location_and_activities_happenings_path(params.except(:controller, :action, :commit).merge(activity_names: (names_array || []) + activity.self_and_used_in_activities.map(&:name))) %>
      <% if activity.self_and_used_in_activities.length > 1 %>
        <div class='dropdown-item'>
          <%= link_to activity.name, add_path, class: 'dropdown-item--inline' %>
          <%= link_to '∈', add_related_path, class: 'btn btn-small btn-info dropdown-item--inline', title: t('activity_name_and_used_in_activities_name', activity_name: activity.name, activities_name: activity.self_and_used_in_activities.map(&:name).to_sentence) %>
        </div>
      <% else %>
        <%= link_to activity.name, add_path, class:'dropdown-item' %>
      <% end %>
    <% end %>
  </div>
</div>

<%= @datatable.render_html search_for_location_and_activities_happenings_path(activity_names: names_array, format: :json) %>

app/views/happenings/show.html.erb
<%
  breadcrumb Happening.model_name.human(count: 2) => happenings_path(search_happenings: { activity_id: '' }), @happening.name => nil
%>
<% if Const.common[:show_ads] %>
  <div class='card bg-light mb-2'>
    <div class='card-body'>
      <h2><%= t('ad_on_top') %></h2>
      <p>
        <%= t('ad_on_top_description') %>
        <%= link_to t('get_in_touch'), contact_path %>
      </p>
    </div>
  </div>
<% end %>
<div class='card'>
  <div class='card-body'>
    <div class='row'>
      <div class='col'>
        <%= detail_view_list @happening, *(Happening::FIELDS - %i[end_date recurrence]), skip_blank: :all %>
        <%= detail_view_list do %>
          <% if @happening.end_date != @happening.start_date %>
            <%= detail_view_one Happening.human_attribute_name(:end_date), @happening.end_date %>
          <% end %>
          <%= detail_view_one Happening.human_attribute_name(:recurrence), @happening.recurrence.to_s %>
        <% end %>
        <h4><%= Discipline.model_name.human(count: @happening.discipline_happenings.size) %></h4>
        <% @happening.discipline_happenings.each do |discipline_happening| %>
          <%= discipline_happening.start_time.to_s :short %>
          <%= discipline_happening.full_name %>
          <br>
          <% discipline_happening.discipline_happening_tags.each do |discipline_happening_tag| %>
            <span class='badge badge-primary'><%= discipline_happening_tag.tag.name %></span>
          <% end %>
        <% end %>
        <%= link_to @happening.club.name, club_path(@happening.club) %>
      </div>
      <div class='col'>
        <%= link_to @happening.venue.name, admin_venue_path(@happening.venue) %>
        <div class='map map--300px'
             data-controller='google-map'
             data-google-map-latitude='<%= @happening.venue.latitude %>'
             data-google-map-longitude='<%= @happening.venue.longitude %>'
             data-action='google-map-callback@window->google-map#initMap'
             >
        </div>
      </div>
    </div>
  </div>
</div>
<% if Const.common[:show_ads] %>
  <div class='card bg-light mt-2'>
    <div class='card-body'>
      <h2><%= t('ad_on_bottom') %></h2>
      <p>
        <%= t('ad_on_bottom_description') %>
        <%= link_to t('get_in_touch'), contact_path %>
      </p>
    </div>
  </div>
<% end %>