config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  shallow do
    root 'pages#home'

    devise_for :users, controllers: {
      omniauth_callbacks: 'devise/my_omniauth_callbacks',
      registrations: 'devise/my_registrations',
    }

    authenticate :user, ->(u) { u.superadmin? } do
      mount Sidekiq::Web => '/sidekiq'
    end

    get 'pages/home'
    get 'sign-in-development/:id', to: 'pages#sign_in_development', as: :sign_in_development
    get 'set_locale', to: 'application#set_locale'
    get 'sample-error', to: 'pages#sample_error'
    get 'sample-error-in-javascript', to: 'pages#sample_error_in_javascript'
    get 'sample-error-in-javascript-ajax', to: 'pages#sample_error_in_javascript_ajax'
    post 'notify-javascript-error', to: 'pages#notify_javascript_error'
    get 'sample-error-in-sidekiq', to: 'pages#sample_error_in_sidekiq'
    get '/test', to: 'pages#test'

    resource :contact

    resources :happenings do
      collection do
        post :search
        get :index_for_location_and_activities
        post :search_for_location_and_activities
      end
    end

    resource :my_account do
      get :change_email
      get :change_password
      patch :update_password
      get :change_language
      get :edit
      patch :update
    end

    resources :clubs do
      collection do
        post :search
      end
      member do
        post :search_happenings
      end
    end

    resource :my_club do
      patch :submit_choose
      delete :remove_me_from
    end
    resources :club_users do
      collection do
        post :search
      end
    end

    namespace :admin do
      get 'dashboard', to: 'dashboard#index'
      resources :users
      resources :activities
      resources :clubs do
        resources :activity_clubs
        collection do
          post :search
        end
        member do
          post :search_happenings
        end
        resources :happenings, only: %i[new create]
      end
      resources :venues
      resources :happenings, except: %i[new create] do
        member do
          get :edit_recurrence
          patch :update_recurrence
        end
        collection do
          get :parse_url
        end
        resources :discipline_happenings
      end
      resources :disciplines do
        resources :discipline_requirements
      end
      resources :requirements
    end
  end
end

app/controllers/my_accounts_controller.rb
class MyAccountsController < ApplicationUserController
  def show; end

  def change_email
    render partial: 'change_email', layout: false
  end

  def change_password
    render partial: 'change_password', layout: false
  end

  def change_language
    render partial: 'change_language', layout: false
  end

  def edit
    @user = current_user
    render partial: 'form', layout: false
  end

  def update
    @user = current_user
    partial = 'form'
    partial = params[:partial] if %w[change_email].include? params[:partial]
    update_and_render_or_redirect_in_js @user, _user_params, my_account_path, partial
  end

  def update_password
    @user = current_user
    unless current_user.valid_password? params[:user][:current_password]
      current_user.errors.add(:current_password, t('my_devise.current_password_is_not_correct'))
    end
    notice = t('data_item_name_successfully_updated', item_name: User.human_attribute_name(:password))
    update_and_render_or_redirect_in_js @user, _user_params, my_account_path, 'change_password', notice
    bypass_sign_in current_user if current_user.errors.blank?
  end

  def _user_params
    params.require(:user).permit(
      *User::FIELDS
    )
  end
end

app/views/my_accounts/_change_email.html.erb
<div id='remote-form'>
  <%= bootstrap_form_for current_user, url: my_account_path(partial: 'change_email'), remote: true, layout: :horizontal do |f| %>
    <%= f.email_field :email, autofocus: true, autocomplete: 'email', value: '' %>
    <div class='remote-form__actions'>
      <%= f.submit class: 'btn btn-primary'%>
    </div>
  <% end %>
</div>

app/views/my_accounts/_change_language.html.erb
<% I18n.available_locales.each do |locale| %>
  <p>
    <%= link_to set_locale_path(locale: locale), 'data-turbolinks': false do %>
      <%= t 'emoji', locale: locale %>
      <%= t('language_name', locale: locale) %>
    <% end %>
  </p>
<% end %>

app/views/my_accounts/_change_password.html.erb
<div id='remote-form'>
  <%= bootstrap_form_for current_user, url: update_password_my_account_path, remote: true, layout: :horizontal do |f| %>
    <%= f.password_field :password, autocomplete: 'off', required: true, autofocus: true %>
    <em><%= t 'my_devise.characters_minimum', count: User.password_length.min %></em>

    <%= f.password_field :password_confirmation, autocomplete: 'off', required: true %>

    <%= f.password_field :current_password, autocomplete: 'off', required: true %>
    <i>(<%= t 'my_devise.we_need_your_current_password_to_confirm_your_changes' %>)</i><br>
    <div class='remote-form__actions'>
      <%= f.submit class: 'btn btn-primary'%>
    </div>
  <% end %>
</div>

app/views/my_accounts/_form.html.erb
<div id='remote-form'>
  <%= bootstrap_form_for @user, url: my_account_path, remote: true, layout: :horizontal do |f| %>
    <%= f.text_field :name %>
    <div class='remote-form__actions'>
      <%= f.submit class: 'btn btn-primary'%>
    </div>
  <% end %>
</div>

app/views/my_accounts/show.html.erb
<%
  breadcrumb t('my_account') => nil
%>
<div class='d-flex flex-column flex-md-row'>
  <div class='card m-2'>
    <div class='card-body'>
      <%= button_tag_open_modal edit_my_account_path, pull_right: true %>
      <dl class='row justify-content-start'>
        <%= detail_view current_user, :name, label_class: 'col-sm-4' %>
      </dl>
      <hr>
      <dl class='row justify-content-start'>
        <%= detail_view_one User.human_attribute_name(:email), current_user.email + ' ' + button_tag_open_modal(change_email_my_account_path, text: t('change_item_name', item_name: User.human_attribute_name(:email))), label_class: 'col-sm-4' %>
        <% if current_user.pending_reconfirmation? %>
          <%= detail_view_one '', t('my_devise.currently_waiting_confirmation_for', item: current_user.unconfirmed_email) %>
        <% end %>
        <%= detail_view_one User.human_attribute_name(:password), button_tag_open_modal(change_password_my_account_path, text: t('change_item_name', item_name: User.human_attribute_name(:password))), label_class: 'col-sm-4' %>
        <%= detail_view_one User.human_attribute_name(:locale), t('language_name', locale: current_user.locale) + ' ' + button_tag_open_modal(change_language_my_account_path, text: t('change_item_name', item_name: User.human_attribute_name(:locale))), label_class: 'col-sm-4' %>
      </dl>
      <hr>
      <dl class='row'>
        <%= detail_view_one t('my_devise.unhappy'), button_to(t('my_devise.cancel_my_account'), user_registration_path, data: { confirm: t('are_you_sure') }, method: :delete, class: 'btn btn-outline-danger float-right') %>
      </dl>
    </div>
  </div>
</div>