config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  shallow do
    root 'pages#home'

    devise_for :users, controllers: {
      omniauth_callbacks: 'devise/my_omniauth_callbacks',
      registrations: 'devise/my_registrations',
    }

    authenticate :user, ->(u) { u.superadmin? } do
      mount Sidekiq::Web => '/sidekiq'
    end

    get 'pages/home'
    get 'sign-in-development/:id', to: 'pages#sign_in_development', as: :sign_in_development
    get 'set_locale', to: 'application#set_locale'
    get 'sample-error', to: 'pages#sample_error'
    get 'sample-error-in-javascript', to: 'pages#sample_error_in_javascript'
    get 'sample-error-in-javascript-ajax', to: 'pages#sample_error_in_javascript_ajax'
    post 'notify-javascript-error', to: 'pages#notify_javascript_error'
    get 'sample-error-in-sidekiq', to: 'pages#sample_error_in_sidekiq'
    get '/test', to: 'pages#test'

    resource :contact

    resources :happenings do
      collection do
        post :search
        get :index_for_location_and_activities
        post :search_for_location_and_activities
      end
    end

    resource :my_account do
      get :change_email
      get :change_password
      patch :update_password
      get :change_language
      get :edit
      patch :update
    end

    resources :clubs do
      collection do
        post :search
      end
      member do
        post :search_happenings
      end
    end

    resource :my_club do
      patch :submit_choose
      delete :remove_me_from
    end
    resources :club_users do
      collection do
        post :search
      end
    end

    namespace :admin do
      get 'dashboard', to: 'dashboard#index'
      resources :users
      resources :activities
      resources :clubs do
        resources :activity_clubs
        collection do
          post :search
        end
        member do
          post :search_happenings
        end
        resources :happenings, only: %i[new create]
      end
      resources :venues
      resources :happenings, except: %i[new create] do
        member do
          get :edit_recurrence
          patch :update_recurrence
        end
        collection do
          get :parse_url
        end
        resources :discipline_happenings
      end
      resources :disciplines do
        resources :discipline_requirements
      end
      resources :requirements
    end
  end
end

app/models/club.rb
class Club < ApplicationRecord
  extend Mobility
  translates :name, :long_name

  FIELDS = %i[kind name long_name website email visible_email phone visible_phone national_id visible_national_id].freeze

  enum kind: %i[sport_organization personal]

  attr_accessor :existing_or_new

  belongs_to :venue
  accepts_nested_attributes_for :venue

  has_many :happenings, dependent: :destroy
  has_many :club_users, dependent: :destroy
  # has_many :users, through: :club_users # do not use this since club
  # users can be disabled, so better is to use active_users
  has_many :active_users, -> { where club_users: { position: ClubUser::ACTIVE_POSITIONS } }, through: :club_users, source: :user
  has_many :activity_clubs, dependent: :destroy
  has_many :activities, through: :activity_clubs

  validates :name, :venue, presence: true
end

app/controllers/admin/clubs_controller.rb
class Admin::ClubsController < Admin::BaseController
  before_action :_set_club, except: %i[index search new create]

  def index
    @datatable = ClubsDatatable.new view_context
  end

  def search
    render json: ClubsDatatable.new(view_context)
  end

  def show
    @datatable = HappeningsForClubDatatable.new view_context
  end

  def search_happenings
    render json: HappeningsForClubDatatable.new(view_context)
  end

  def new
    @club = Club.new
    render partial: 'form', layout: false
  end

  def edit
    @club = current_user.club
    render partial: 'form', layout: false
  end

  # JS
  def create
    @club = Club.new
    update_and_render_or_redirect_in_js @club, _club_params, ->(id) { admin_club_path(id) }
  end

  # JS
  def update
    update_and_render_or_redirect_in_js @club, _club_params, admin_club_path(@club)
  end

  def destroy
    @club.destroy!
    redirect_to admin_clubs_path, notice: helpers.t_notice('successfully_deleted', Club)
  end

  def _set_club
    @club = Club.find params[:id]
  end

  def _club_params
    params.require(:club).permit(
      *Club::FIELDS, :existing_or_new, :venue_id,
      venue_attributes: Venue::FIELDS,
    )
  end
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: %i[search]
  before_action :_set_club, except: %i[index search]

  def index
    @datatable = ClubsDatatable.new view_context
  end

  def search
    render json: ClubsDatatable.new(view_context)
  end

  def show
    view_context.params.merge! HappeningsForClubDatatable.param_set 'happenings.start_date', Time.zone.today..(Time.zone.today + 1.year)
    @datatable = HappeningsForClubDatatable.new view_context
  end

  def search_happenings
    render json: HappeningsForClubDatatable.new(view_context)
  end

  def _set_club
    @club = Club.find params[:id]
  end
end

app/views/admin/clubs/_form.html.erb
<div id='remote-form'>
  <%= bootstrap_form_for @club, url: @club.new_record? ? admin_clubs_path : admin_club_path(@club), remote: true, layout: :horizontal do |f| %>
    <div class='row'>
      <div class='col-sm'>
        <%= f.radio_button :kind, :sport_organization, label: Club.human_enum_name(:kind, :sport_organization) %>
        <%= f.radio_button :kind, :personal, label: Club.human_enum_name(:kind, :personal) %>
        <%= f.text_field :name %>
        <%= f.text_field :long_name %>
        <%= f.text_field :website %>
        <%= f.text_field :email %>
        <%= f.check_box :visible_email %>
        <%= f.text_field :phone %>
        <%= f.check_box :visible_phone %>
        <%= f.text_field :national_id %>
        <%= f.check_box :visible_national_id %>
      </div>
      <div class='col-sm'>
        <%= render 'admin/venues/existing_or_new', f: f %>
      </div>
    </div>
    <div class='remote-form__actions'>
      <% unless @club.new_record? %>
        <%= link_to admin_club_path(@club), method: :delete, 'data-confirm': t_are_you_sure_to_remove_item_name(@club.name), title: t_crud('delete', Club) do %>
          <i class="demo-icon icon-trash-empty text-danger" aria-hidden="true"></i>
        <% end %>
      <% end %>
      <%= f.submit class: 'btn btn-primary'%>
    </div>
  <% end %>
</div>

app/views/admin/clubs/index.html.erb
<%
  breadcrumb Club.model_name.human(count: 2) => nil
%>

<%= button_tag_open_modal new_admin_club_path do %>
  <i class="demo-icon icon-plus" aria-hidden="true"></i>
  <%= t_crud('add_new', Club) %>
<% end %>
<br>
<%= @datatable.render_html search_admin_clubs_path(format: :json) %>

app/views/admin/clubs/show.html.erb
<%
  breadcrumb Club.model_name.human(count: 2) => admin_clubs_path, @club.name => nil
%>
<div class='card'>
  <div class='card-body'>
    <%= button_tag_open_modal edit_admin_club_path(@club), title: t_crud('edit', Club), pull_right: true %>
    <div class='row'>
      <div class='col'>
        <%= detail_view_list @club, *Club::FIELDS %>
      </div>
      <div class='col'>
        <%= link_to @club.venue.name, admin_venue_path(@club.venue) %>
        <div class='map map--50percent'
             data-controller='google-map'
             data-google-map-latitude='<%= @club.venue.latitude %>'
             data-google-map-longitude='<%= @club.venue.longitude %>'
             data-action='google-map-callback@window->google-map#initMap'
             >
        </div>
      </div>
    </div>
    <%= button_tag_open_modal new_admin_club_activity_club_path(@club) do %>
      <i class="demo-icon icon-plus" aria-hidden="true"></i>
      <%= t_crud('add_new', ActivityClub) %>
    <% end %>
    <div class='card-deck'>
      <% @club.activity_clubs.each do |activity_club| %>
        <div class='card card--text'>
          <div class='card-body'>
            <%= button_to 'X', admin_activity_club_path(activity_club), class: 'btn btn-sm btn-outline-danger btn--no-padding px-1 edit-button', title: t_crud('delete', ActivityClub), method: :delete, 'data-confirm': t('are_you_sure') %>
            <%= link_to activity_club.activity.name, admin_activity_path(activity_club.activity) %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<div class='box'>
  <%= button_tag_open_modal new_admin_club_happening_path(@club) do %>
    <i class="demo-icon icon-plus" aria-hidden="true"></i>
    <%= t_crud('add_new', Happening) %>
  <% end %>
  <%= @datatable.render_html search_happenings_admin_club_path(@club, format: :json) %>
</div>