config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  shallow do
    root 'pages#home'

    devise_for :users, controllers: {
      omniauth_callbacks: 'devise/my_omniauth_callbacks',
      registrations: 'devise/my_registrations',
    }

    authenticate :user, ->(u) { u.superadmin? } do
      mount Sidekiq::Web => '/sidekiq'
    end

    get 'pages/home'
    get 'sign-in-development/:id', to: 'pages#sign_in_development', as: :sign_in_development
    get 'set_locale', to: 'application#set_locale'
    get 'sample-error', to: 'pages#sample_error'
    get 'sample-error-in-javascript', to: 'pages#sample_error_in_javascript'
    get 'sample-error-in-javascript-ajax', to: 'pages#sample_error_in_javascript_ajax'
    post 'notify-javascript-error', to: 'pages#notify_javascript_error'
    get 'sample-error-in-sidekiq', to: 'pages#sample_error_in_sidekiq'
    get '/test', to: 'pages#test'

    resource :contact

    resources :happenings do
      collection do
        post :search
        get :index_for_location_and_activities
        post :search_for_location_and_activities
      end
    end

    resource :my_account do
      get :change_email
      get :change_password
      patch :update_password
      get :change_language
      get :edit
      patch :update
    end

    resources :clubs do
      collection do
        post :search
      end
      member do
        post :search_happenings
      end
    end

    resource :my_club do
      patch :submit_choose
      delete :remove_me_from
    end
    resources :club_users do
      collection do
        post :search
      end
    end

    namespace :admin do
      get 'dashboard', to: 'dashboard#index'
      resources :users
      resources :activities
      resources :clubs do
        resources :activity_clubs
        collection do
          post :search
        end
        member do
          post :search_happenings
        end
        resources :happenings, only: %i[new create]
      end
      resources :venues
      resources :happenings, except: %i[new create] do
        member do
          get :edit_recurrence
          patch :update_recurrence
        end
        collection do
          get :parse_url
        end
        resources :discipline_happenings
      end
      resources :disciplines do
        resources :discipline_requirements
      end
      resources :requirements
    end
  end
end

app/models/happening.rb
class Happening < ApplicationRecord
  extend Mobility
  translates :name, :description

  FIELDS = %i[name description website recurrence start_date end_date].freeze

  serialize :recurrence
  attr_accessor :existing_or_new

  belongs_to :venue
  accepts_nested_attributes_for :venue
  belongs_to :club

  has_many :discipline_happenings, dependent: :destroy

  validates :name, :start_date, :end_date, presence: true
  validate :_end_date_greater_or_equal_start_date

  before_validation :_default_values_on_create, on: :create

  def _end_date_greater_or_equal_start_date
    return if end_date.blank? || start_date.blank?
    return if end_date >= start_date

    errors.add :end_date, t('can_not_be_less_than_item_name', item_name: Happening.human_attribute_name(:start_date))
  end

  def multi_day?
    end_date != start_date
  end

  def _default_values_on_create
    self.end_date ||= start_date
  end
end

app/controllers/admin/happenings_controller.rb
class Admin::HappeningsController < Admin::BaseController
  before_action :_set_happening, except: %i[index new create parse_url]

  def index
    @happenings = Happening.all
  end

  def show; end

  def new
    @happening = Happening.new(
      club_id: params[:club_id]
    )
    render partial: 'form', layout: false
  end

  def edit
    render partial: 'form', layout: false
  end

  def edit_recurrence
    @recurrence_form = RecurrenceForm.new(
      happening: @happening,
      day: @happening.start_date.wday,
      every: t('recurrences_every').first.first,
      total: 1,
      hour: @happening.discipline_happenings.order(start_time: :asc).first&.start_time&.hour,
      min: @happening.discipline_happenings.order(start_time: :asc).first&.start_time&.min,
    )
    render partial: 'recurrence_form', layout: false
  end

  def update_recurrence
    @recurrence_form = RecurrenceForm.new(
      *_recurrence_form_params.merge(
        happening: @happening,
      )
    )
    return if params[:button] == 'preview'

    update_and_render_or_redirect_in_js(
      @recurrence_form,
      _recurrence_form_params, admin_happening_path(@happening),
      'recurrence_form',
      helpers.t_notice_count('successfully_created', Happening, @recurrence_form.preview.size),
    )
  end

  # JS
  def create
    @happening = Happening.new(
      club_id: params[:club_id]
    )
    update_and_render_or_redirect_in_js @happening, _happening_params, ->(id) { admin_happening_path(id) }
  end

  # JS
  def update
    update_and_render_or_redirect_in_js @happening, _happening_params, admin_happening_path(@happening)
  end

  def destroy
    @happening.destroy!
    redirect_to admin_happenings_path, notice: helpers.t_notice('successfully_deleted', Happening)
  end

  def parse_url
    result = ParseUrl.new(params[:url]).perform
    if result.success?
      render json: result.data[:json]
    else
      render json: { error: result.message }
    end
  end

  def _set_happening
    @happening = Happening.find params[:id]
  end

  def _happening_params
    params.require(:happening).permit(
      *Happening::FIELDS, :existing_or_new, :venue_id, :club_id,
      venue_attributes: Venue::FIELDS,
    )
  end

  def _recurrence_form_params
    params.require(:recurrence_form).permit(*RecurrenceForm::FIELDS)
  end
end

app/controllers/happenings_controller.rb
class HappeningsController < ApplicationController
  before_action :_set_happening, except: %i[index index_for_location_and_activities search_for_location_and_activities]

  def index
    redirect_to root_path
  end

  def index_for_location_and_activities
    @datatable = HappeningsForActivityNamesDatatable.new view_context
  end

  def search_for_location_and_activities
    render json: HappeningsForActivityNamesDatatable.new(view_context)
  end

  def show; end

  def _set_happening
    @happening = Happening.find params[:id]
  end

  def _happening_params
    params.require(:happening).permit(
      *Happening::FIELDS, :existing_or_new, :venue_id, :club_id,
      venue_attributes: Venue::FIELDS,
    )
  end

  def _search_happenings_params
    params.require(:search_happenings).permit(
      :venue_id, :activity_id
    )
  end
end

app/views/admin/happenings/_form.html.erb
<div id='remote-form'>
  <% if @happening.new_record? %>
    <%= bootstrap_form_with url: parse_url_admin_happenings_path, layout: :horizontal, html: { 'data-controller': 'form'} do |f| %>
      <%= f.text_field :url, label: "Url <span class='d-none-opacity' data-target='form.processing'><i class='demo-icon icon-spin4 animate-spin'></i> fetching data...</span>".html_safe, placeholder: 'https://www.facebook.com/events/...', 'data-target': 'form.parameter', 'data-action': 'blur->form#submit_ajax_and_update change>form#submit_ajax_and_update keyup->form#submit_ajax_and_update' %>
    <% end %>
  <% end %>
  <%= bootstrap_form_for @happening, url: @happening.new_record? ? admin_club_happenings_path(@happening.club) : admin_happening_path(@happening), remote: true, layout: :horizontal do |f| %>
    <div class='row'>
      <div class='col-sm'>
        <%= f.text_field :name %>
        <%= f.date_field :start_date, help: !f.object.multi_day? && add_alternative_helper(Happening.human_attribute_name(:end_date), '#end_date') %>
        <div id='end_date' class='<%= 'd-none-display' unless f.object.multi_day? %>'>
          <%= f.date_field :end_date %>
        </div>
        <%= f.text_field :website %>
        <%= f.text_area :description %>
      </div>
      <div class='col-sm'>
        <%= render 'admin/venues/existing_or_new', f: f %>
      </div>
    </div>
    <div class='remote-form__actions'>
      <% unless @happening.new_record? %>
        <%= link_to admin_happening_path(@happening), method: :delete, 'data-confirm': t_are_you_sure_to_remove_item_name(@happening.name), title: t_crud('delete', Happening) do %>
          <i class="demo-icon icon-trash-empty text-danger" aria-hidden="true"></i>
        <% end %>
      <% end %>
      <%= f.submit class: 'btn btn-primary'%>
    </div>
  <% end %>
</div>

app/views/admin/happenings/_recurrence_form.html.erb
<div id='remote-form'>
  <%= bootstrap_form_for @recurrence_form, url: update_recurrence_admin_happening_path(@happening), remote: true, layout: :horizontal, method: :patch do |f| %>
    <div class='row'>
      <div class='col-sm'>
        <%= f.select :every, t('recurrences_every').invert %>
        <%= f.select :day, t('date.day_names').map.with_index.map { |d, i| [d, i] } %>
        <%= f.select :month, t('date.month_names') %>
        <%= f.text_field :custom_name, placeholder: "{{number}} name" %>
      </div>
      <div class='col-sm'>
        <%= f.select :hour, 0..23 %>
        <%= f.select :min, 0..59 %>
        <%= f.number_field :total %>
        <%= f.number_field :start_number %>
      </div>
    </div>
    <hr>
    <%= render 'recurrence_preview' %>
    <div class='remote-form__actions'>
      <%= f.button t('show'), value: 'preview', class: 'btn btn-success'%>
      <%= f.submit t('create'), class: 'btn btn-primary'%>
    </div>
  <% end %>
</div>

app/views/admin/happenings/_recurrence_preview.html.erb
<div id='preview'>
  <%=j @recurrence_form.preview.join('<br>').html_safe %>
</div>

app/views/admin/happenings/index.html.erb
<%
  breadcrumb Happening.model_name.human(count: 2) => nil
%>

<% @happenings.each do |happening| %>
  <%= link_to happening.name, admin_happening_path(happening) %>
  <br>
<% end %>

app/views/admin/happenings/show.html.erb
<%
  breadcrumb Happening.model_name.human(count: 2) => admin_happenings_path, @happening.name => nil
%>
<div class='card'>
  <div class='card-body'>
    <%= button_tag_open_modal edit_admin_happening_path(@happening), title: t_crud('edit', Happening), pull_right: true %>
    <div class='row'>
      <div class='col-md'>
        <%= detail_view_list @happening, *(Happening::FIELDS - [:recurrence]) %>
        <%= detail_view_list do %>
          <%= detail_view_one Happening.human_attribute_name(:recurrence) do %>
            <%= @happening.recurrence.to_json %>
            <%= button_tag_open_modal edit_recurrence_admin_happening_path(@happening), title: t('edit_item_name', item_name: Happening.human_attribute_name(:recurrence)) %>
          <% end %>
        <% end %>
        <%= link_to @happening.club.name, admin_club_path(@happening.club) %>
      </div>
      <div class='col-md'>
        <%= link_to @happening.venue.name, admin_venue_path(@happening.venue) %>
        <div class='map map--300px'
             data-controller='google-map'
             data-google-map-latitude='<%= @happening.venue.latitude %>'
             data-google-map-longitude='<%= @happening.venue.longitude %>'
             data-action='google-map-callback@window->google-map#initMap'
             >
        </div>
      </div>
    </div>
  </div>
</div>
<%= button_tag_open_modal new_admin_happening_discipline_happening_path(@happening) do %>
  <i class="demo-icon icon-plus" aria-hidden="true"></i>
  <%= t_crud('add_new', DisciplineHappening) %>
<% end %>
<div class='card-deck'>
  <% @happening.discipline_happenings.each do |discipline_happening| %>
    <div class='card card--text mb-4'>
      <div class='card-body'>
        <%= button_tag_open_modal edit_admin_discipline_happening_path(discipline_happening), title: t_crud('edit', DisciplineHappening), pull_right: true %>
        <%= detail_view_list discipline_happening, *(DisciplineHappening::FIELDS - [:price_without_discount_cents]), skip_blank: :all %>
        <% discipline_happening.discipline_happening_tags.each do |discipline_happening_tag| %>
          <span class='badge badge-primary'><%= discipline_happening_tag.tag.name %></span>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/happenings/update_recurrence.js.erb
var form = document.getElementById('preview');
var parent = form.parentNode;
var new_form = document.createElement('div');
new_form.innerHTML = '<%=j render 'recurrence_preview' %>';
parent.replaceChild(new_form, form);